# Generated by Django 4.2 on 2023-04-20 05:45

from django.db import migrations, models
import myblog.models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='posts/default.jpg', upload_to=myblog.models.upload_to, verbose_name='Image'),
        ),
    ]
